### ISSUE TITLE
Developer/contributors over time

### ISSUE THREAD

**Issue by llrs** [lgatto/biocpkgs#2]
I have some interest on the metadata of Bioconductor (see [here](https://llrs.github.io/BiocStats/) for my analysis/comments) and I read your [comment](https://lgatto.github.io/RforProteomics/articles/biocprot.html#fn1) on the vignette (To RforProteomics):
> It would be interesting to also map the number of new developer/contributors over time

How would you gather the data of developers/contributors?

One option would be to read all the DESCRIPTION files of the repositories on git.bioconductor. But that would left out developers without packages in Bioconductor release. Is there some (public) metadata file (like the one you noted on #1 but) for contributors/maintainers?

**Comment by lgatto** [comment]
I have done it for [`MSnbase`](https://lgatto.github.io/msnbase-contribs/), but that's by parsing my git repository and fetch to commits identifying the respective contributions. 

The *easiest* I can think of is to do if at the Bioconductor version level, i.e. checking out `RELEASE_3_6`, `RELEASE_3_5`, ... (there's a package to checkout different branches in R, probably `gitr`, but not sure), and then use something like [`biocpkgs::ncontribs`](https://github.com/lgatto/biocpkgs/blob/master/R/contribs.R) - assuming there's an `Authors@R` field - to count).

**Comment by llrs** [comment]
I might end up using this [solution](https://stackoverflow.com/questions/1125476/retrieve-a-single-file-from-a-repository), because I don't want to install (or store) all the packages (and all the versions) of Bioconductor in my computer. 

Thanks for your answer!

**Comment by lgatto** [comment]
Keep me posted!
